parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - wantora

env:
  es6: true
  browser: true
  commonjs: true
  webextensions: true

globals:
  process: false
  content: false
  cloneInto: false

overrides:
  - files:
      - webpack.config.js
      - scripts/*.js
    parserOptions:
      sourceType: script
    env:
      browser: false
      node: true
